### ISSUE TITLE
issues with kmtest.h

### ISSUE THREAD

**Issue by aadit0402** [SergiusTheBest/kmtest#8]
i am compiling this sample test but facing compiler error with this line while building the code. 

extern "C" inline NTSTATUS DriverEntry(_In_ DRIVER_OBJECT* driverObject, _In_ PUNICODE_STRING registryPath)

unexpected )' with _In_ DRIVER_OBJECT *driverObject.

how to resolve this issue?

i am using vs2015 with 15063 wdk and sdk.

**Comment by SergiusTheBest** [comment]
@aadit0402  Could you post a screenshot or the error?

**Comment by aadit0402** [comment]
Thanks for the response SergiusTheBest

in the addtest.cpp file, most of the error is pointing to these two line: 

SCENARIO("Addition operation") 
{

these are the errors:
syntax error: identifier curClause
curClause: undeclared identifier
nextClause undeclared identifier
'initializing can not convert from 'void (__stdcall *)(kmtest::Clause)' to 'kmtest::TestFunc

KMTEST is not a class or namespace name

While looking at these error, i think i have done some silly mistakes but i am unable to figure it out.

Thanks in advance.

**Comment by SergiusTheBest** [comment]
@aadit0402 Did you manage to resolve the issue? I tried building with VS2015 and it worked fine (except the warning 4100 in `MulTest.cpp`).

**Comment by aadit0402** [comment]
Hi SergiusTheBest/kmtest,

Thanks for looking into the request. I am still facing the same issue. I am
using visual studio 2015 with wdk and sdk 15063.
I have just moved the kmtest.h file to the same place where my src files
are placed. It is just a single directory. I am suspecting this could also
cause this "syntax error issue".

 I am still figuring out the root cause of these issues. Thanks again for
looking into this.

Thanks,
Aditya

**Comment by SergiusTheBest** [comment]
@aadit0402 Could you zip your project and attach here?

**Comment by aadit0402** [comment]
Please find the attached project source files. These two files I have not
included in this attachment: .sln and .vcxproj

This is the format I have planned to use for my project.

**Comment by SergiusTheBest** [comment]
@aadit0402 The attachment is missing. Probably you need to add it using the GitHub.

**Comment by aadit0402** [comment]
closing the issue. I am able to build it. Some project configurations i was missing. now after fresh clone and with wdk 15063, it worked. Thanks @SergiusTheBest :)
